name: Convo CI
run-name: Continuous Integration of Convo
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v5

      - name: Set up JDK 17 for project
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build project
        env:
          APPLICATION_NAME: ${{ vars.APPLICATION_NAME }}
          APPLICATION_PORT: ${{ vars.APPLICATION_PORT }}
          DB_HOST: ${{ vars.DB_HOST }}
          DB_USERNAME: ${{ vars.DB_USERNAME }}
          DB_PASSWORD: ${{ vars.DB_PASSWORD }}
          EUREKA_HOSTNAME: ${{ vars.EUREKA_HOSTNAME }}
          EUREKA_DEFAULT_ZONE: ${{ vars.EUREKA_DEFAULT_ZONE }}
        run: mvn --batch-mode --update-snapshots verify

      - name: Create a directory and copy result to it.
        run: mkdir build && cp target/*.war build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: convo-package
          path: build